### ISSUE TITLE
Error: Invalid or corrupt jarfile QoRTs.jar

### ISSUE THREAD

**Issue by misik** [hartleys/QoRTs#10]
I get the Error: Invalid or corrupt jarfile QoRTs.jar with QoRTs 1.0.7 when I run the command:

 java -jar QoRTs.jar.1 QC --man

**Comment by hartleys** [comment]
Why do you have a ".1" on the end of the jarfile name?

java -jar QoRTs.jar**.1** QC --man

I think I've seen that before from when you partially download a file on certain browsers/OS's. Maybe re-download it and make sure it's actually named "QoRTs.jar"? The file should be 7.207mb.

**Comment by misik** [comment]
Ok, this site has a link to the truncated file but I could download the full file when I copied the link from "view the full file" hyperlink. Thank you.
