### ISSUE TITLE
Attribute: "1"" is misformatted! Does not contain the break value: "\s+" pairString.split.length=1

### ISSUE THREAD

**Issue by robrs66** [hartleys/QoRTs#12]
Hi hartley
It seems to be that there is some small issue in the reading of the GTF file. In my case I took it from here: ftp://ftp.ensemblgenomes.org/pub/release-10/plants/gtf/arabidopsis_thaliana/

The file is: ftp://ftp.ensemblgenomes.org/pub/release-10/plants/gtf/arabidopsis_thaliana/Arabidopsis_thaliana.TAIR10.gtf.gz

This file looks like this:
Mt	protein_coding	exon	273	734	.	-	.	 gene_id "ATMG00010"; transcript_id "ATMG00010.1"; exon_number "1"; gene_name "ORF153A"; transcript_name "ATMG00010.1"; seqedit "false";
Mt	protein_coding	CDS	276	734	.	-	0	 gene_id "ATMG00010"; transcript_id "ATMG00010.1"; exon_number "1"; gene_name "ORF153A"; transcript_name "ATMG00010.1"; protein_id "ATMG00010.1";
Mt	protein_coding	start_codon	732	734	.	-	0	 gene_id "ATMG00010"; transcript_id "ATMG00010.1"; exon_number "1"; gene_name "ORF153A"; transcript_name "ATMG00010.1";

I could read it into R by using the "import" function from the R/Bioconductor package "rtracklayer". This yields a nice GRanges object with the annotation. Then I save it by using the "export" function, but the problem still persists. 

Could you please have a look at this small issue? Perhaps you can see where the problem is.
Best,
Rob

**Comment by hartleys** [comment]
It looks like they decided that it was a good idea to use semicolons in gene names. Semicolons are the delimiter used by (almost all) GTF formatted files (GTF is actually a bunch of file formats that are *almost* the same). I've seen problems with semicolons before, but I've never seen one in a gene name before.

See the gene named "CYCD7;1".

If you have textpad or know how to use POSIX regular expresions you can find (and replace) all the offending elements using the regex:
"\([^[:space:]]*\);\([^[:space:]]*\)"

But I suppose it depends on what you want to replace the semicolons with . . .

**Comment by robrs66** [comment]
Thank you very much Hartleys. I have followed your suggestions and the problem is solved.

**Comment by hartleys** [comment]
Happy to help!

**Comment by hartleys** [comment]
The newest version of QoRTs now parses gene ID's (and other attributes/tags) that contain semicolons. It then automatically replaces all semicolons with underscores.
