### ISSUE TITLE
LICENSE for the QoRTs R package

### ISSUE THREAD

**Issue by tomsing1** [hartleys/QoRTs#13]
The [LICENCE](https://github.com/hartleys/QoRTs/blob/master/src/QoRTs/LICENSE) file for the QoRTs R package contains a note regarding the QoRTs.jar scala content, but that content is actually not part of the R package. 

Would it be possible to create a separate LICENSE file for the R package, without reference? It would make keeping track of the different licensing conditions easier.

**Comment by hartleys** [comment]
I can do that, no problem. It will be in the next release.

**Comment by hartleys** [comment]
The new version of QoRTs has been updated as requested.
