### ISSUE TITLE
Inconsistent delimiters in QC.summary.txt

### ISSUE THREAD

**Issue by tomsing1** [hartleys/QoRTs#14]
The QC.summary.txt file is tab-delimited, except for three fields:

- minObservedReadLength
- maxObservedReadLength
- maxLegalPhredScore

which are separated from their values by two spaces instead of a tab stop. 
Perhaps these fields should also be tab-separated?

**Comment by hartleys** [comment]
Good catch. I'm surprised I never saw it before. I'll fix this and fold it into the next release (probably released next week).

**Comment by hartleys** [comment]
The newest version of QoRTs fixes this bug.
