### ISSUE TITLE
Count discrepency

### ISSUE THREAD

**Issue by royfrancis** [hartleys/QoRTs#15]
In `geneCounts`, the the summed value of `COUNT_CDS` and `COUNT_UTR` for genes have a certain value. In `summary` the  `ReadPairs_UniqueGene_CDS` and `ReadPairs_UniqueGene_UTR` have reverse values from that of `geneCounts`.

**Comment by hartleys** [comment]
Ouch. Yes. This is a bug. The summary file is correct, the geneCounts file has them switched.

There will be a new release later today or tomorrow with a few other added features. I'll fix this as well.

Thanks for the catch!

**Comment by hartleys** [comment]
This issue is fixed in the new release (v1.1.2). Thanks again!
