### ISSUE TITLE
biotype coverage graph

### ISSUE THREAD

**Issue by remouski** [hartleys/QoRTs#18]
Hi,

First, thanks for coming up with this, very useful.

I was wondering if it would be possible to modify the makePlot.biotype.rates so the user can input a vector of biotypes he/she would like to see in the graph. 

Maybe also create another function that list the biotypes present in all samples of a project?

Cheers,

Remi

**Comment by hartleys** [comment]
Easy enough. The next release will include two new options for the makePlot.biotype.rates function.

* Parameter "showTypes" can be used to set up a list of biotypes to plot.
* Adding "plot = FALSE" will suppress plotting and instead just return the data table. This can be used with the "colnames" function to get the list of biotypes.

The code is ready. I'll post a release once it's passed testing.

**Comment by hartleys** [comment]
The new release (v1.1.8) contains the two options mentioned above.

Examples for how to use these new options:

    library("QoRTs");
    #Get the example dataset:
    directory <- paste0(system.file("extdata/", package="QoRTsExampleData",
                        mustWork=TRUE),"/");
    decoder.file <- system.file("extdata/decoder.txt",
                                package="QoRTsExampleData",
                                mustWork=TRUE);
    decoder.data <- read.table(decoder.file,
                               header=T,
                               stringsAsFactors=F);
    #Load the dataset into qorts:
    res <- read.qc.results.data(directory, decoder = decoder.data,
                                calc.DESeq2 = TRUE, calc.edgeR = TRUE);
    #make a plotter:
    byLane.plotter <- build.plotter.colorByLane(res);

    #Normal biotype plot:
    makePlot.biotype.rates(byLane.plotter);

    #Only show a few specific biotypes:
    makePlot.biotype.rates(byLane.plotter, 
                           showTypes = c("protein_coding",
                                         "misc_RNA",
                                         "Mt_rRNA",
                                         "pseudogene"));

    #return a data table:
    makePlot.biotype.rates(byLane.plotter, plot=FALSE);

    #return a list of biotypes:
    rownames(makePlot.biotype.rates(byLane.plotter, plot=FALSE));
