### ISSUE TITLE
GTF format

### ISSUE THREAD

**Issue by colindaven** [hartleys/QoRTs#2]
Hi,

is there an example GTF format file somewhere which is not in the huge tarball ?

I got the following error with GTF files generated by a) CDS alignment with gmap followed by b) conversion from GFF3 to GTF with ngstutils gtfutils fromgff.

  OutputGtfLine checkFmt: Attribute: "ID=g11.t1.mrna1.exon1" is misformatted! Does not contain the break value: "\s+" pairString.split.length=1

# Full format:

  SBK3v2  SBKv2con_gmap   gene    11220736        11221762        .       -       .       ID=g11.t1.path1;    Name=g11.t1
  SBK3v2  SBKv2con_gmap   mRNA    11220736        11221762        .       -       .       ID=g11.t1.mrna1;Name=g11.t1;Parent=g11.t1.path1;coverage=100.0;identity=100.0
  SBK3v2  SBKv2con_gmap   exon    11220736        11221762        100     -       .       ID=g11.t1.mrna1.exon1;Name=g11.t1;Parent=g11.t1.mrna1;Target=g11.t1 1 1027 +
  SBK3v2  SBKv2con_gmap   CDS     11220736        11221762        100     -       .       ID=g11.t1.mrna1.cds1;Name=g11.t1;Parent=g11.t1.mrna1;Target=g11.t1 1 1027 +

**Comment by hartleys** [comment]
I use the UCSC definition of the GTF format, found here:
https://genome.ucsc.edu/FAQ/FAQformat.html#format3

Note that the key/value pairs in that last column are separated by semicolons, and then the keys and values themselves are separated by spaces. In your example, they keys and values are separated by "=".

For your reference, I have placed a copy of the annotation file used with the example dataset here:
http://hartleys.github.io/QoRTs/anno.gtf.gz
Note that it's straight from Ensembl, but only covers select regions of the genome (as the example dataset was stripped down to reduce file size).

Hope this helps!
Steve

**Comment by colindaven** [comment]
Thanks Steve,

that was very helpful.

Cheers,
Colin

**Comment by colindaven** [comment]
Appears to be working, cheers
