### ISSUE TITLE
Extract raw information for Read Mapping Location Rates

### ISSUE THREAD

**Issue by davemcg** [hartleys/QoRTs#23]
Hi Steve, could you explain how I could extract ALL of the values from field t "Read Mapping Location Rates?" I tried diving into the qorts structure but it looked like I could only extract the information one sample at a time.

**Comment by hartleys** [comment]
In the standard pipeline, when you do the command makeMultiplot.all, it will create a file "summary.table.txt". This table will include rows containing all the information you seek for each sample/replicate.

The rows you want are named:

     ReadPairs_AmbigGene
     ReadPairs_UniqueGene
     ReadPairs_UniqueGene_CDS
     ReadPairs_UniqueGene_UTR
     ReadPairs_NoGene
     ReadPairs_NoGene_Intron
     ReadPairs_NoGene_OneKbFromGene
     ReadPairs_NoGene_TenKbFromGene
     ReadPairs_NoGene_MiddleOfNowhere

You can also generate this file manually using the [get.summary.table](http://hartleys.github.io/QoRTs/Rhtml/get.summary.table.html) command:

     get.summary.table(res,outfile="summary.table.txt");

Is this what you were looking for?

**Comment by davemcg** [comment]
YES. Is 'READ_PAIR_OK' the denominator?

**Comment by hartleys** [comment]
Yes.
