### ISSUE TITLE
Feature request: subsample alignments

### ISSUE THREAD

**Issue by tomsing1** [hartleys/QoRTs#26]
QoRTs is great, but I find performing QC on a full BAM file takes quite some time, exceeding that of any other steps in my workflow. Usually, I subsample from the bam file (e.g. using samtools) and perform QC on the sample only. 

Would the option to subsample either a fixed number of reads or a fraction of the reads (keeping pairs intact) be a useful addition to QoRTs?

**Comment by hartleys** [comment]
Hmm. Should be an easy addition.

I'm currently in the process of a major upgrade to QoRTs to add an array of new QC metrics (v1.2.0). It may be some time before the new version is fully tested and ready for release, but I'll make sure to include this feature.

**Comment by hartleys** [comment]
You can now tell QoRTs to subsample a certain percentage of the reads using the --randomSubsample X parameter. X is a floating-point number between 0 and 1 (default is 1).

You can also specify the random seed using the parameter "--randomSeed". This allows you to rerun the analysis and get the exact same result.

**Comment by tomsing1** [comment]
Great, thanks a lot!
