### ISSUE TITLE
Feature request: Allowing you to specify a prefix to output files

### ISSUE THREAD

**Issue by c-guzman** [hartleys/QoRTs#27]
It might already exist and I can't seem to find it. The `--title` flag seems to be the closest, but it doesn't do specifically what I require.

I run a lot of samples through a nextflow pipeline, unfortunately the naming convention of the single-bam QC output all start with QC.* making it impossible to tell files apart and occasionally breaking the pipeline. Is it possible to allow a prefix to the output files?

**Comment by hartleys** [comment]
This will be included in release 1.2 using the parameter "--outfilePrefix".

**Comment by hartleys** [comment]
With version 1.2.19, you can now specify the filename prefix at the QC command using the parameter "--outfilePrefix myprefix".

In the R companion package, you will need to specify the prefixes by adding a new column to the decoder titled "qc.data.prefix".
