### ISSUE TITLE
Efficiency tips

### ISSUE THREAD

**Issue by royfrancis** [hartleys/QoRTs#34]
I have single-cell rna-seq data from thousands of cells and I was contemplating running qorts on all of them. I am mostly interested in the counts, qc metrics (gene body coverage etc) and summary info. The number of reads per sample is low though (mostly less than 1 mil reads). And I am trying to be as efficient as possible. 

For example, I noticed that a flat gff is created during run, So I created that initially and provide that as `flatgff` hoping that would save some time. I also removed generate plots, multiplot etc which I usually use.  I noticed that although 48GB of RAM is provided, run time print outs show `[Mem usage: [10GB / 19GB]] `. Below is the code I currently use.

```
java -Xmx48G -jar qorts-1.2.26.jar QC \
	--singleEnded \
	--noGzipOutput \
	--verbose \
	--maxReadLength 50 \
	--maxPhredScore 100 \
	--minMAPQ 255 \
	--flatgff dr-flat-unstranded.gff" \
	sample.bam \
	dr.gtf \
	"qorts-sample"
```
If `flatgff` is provided, do I still have to provide the standard gtf argument?
Are there any other tips that could speed things up? Uncritical things I could turn off etc?

**Comment by hartleys** [comment]
Even if you include a "flattened" GFF, you still also need to provide the standard GTF.

There are a ton of optional modules you can shut off to greatly reduce runtime.

See the (QC command doc)(http://hartleys.github.io/QoRTs/jarHtml/QC.html). See the section at the bottom on "Sub-Functions". I can't easily say which functions are "critical", it depends entirely on what QC metrics you think are relevant. The NVC in particular is very slow, and you can deactivate it using the parameter:

"--skipFunctions NVC,writeClippedNVC"

But if you're using the NVC plots, then obviously you don't want to exclude them.

As for the amount of memory used, I'm afraid that depends on too many factors for me to guess. You're going to have to test it out with your own data.

**Comment by royfrancis** [comment]
Thanks!
