### ISSUE TITLE
highlight Group

### ISSUE THREAD

**Issue by remouski** [hartleys/QoRTs#37]
Hi,

If it's not too difficult, highlighting a group could come in handy from time to time.

Tx.

**Comment by hartleys** [comment]
I'm currently putting together a more flexible plotter builder function that will let you color and highlight anything you want. It'll be in the next release, probably in a week or two.

**Comment by hartleys** [comment]
I have added a new function to the R package called [build.plotter.advanced](http://hartleys.github.io/QoRTs/Rhtml/build.plotter.html) which allows you to set more flexible highlighting and coloring.

For example, to highlight the CASE group in the example dataset, use the commands:

    data(res,package="QoRTsExampleData");
    library("QoRTs")
    plotter <- build.plotter.advanced(res, 
              highlightBy = res@decoder$group.ID,
              highlight = "CASE");
    makeMultiPlot.withPlotter(plotter);

**Comment by remouski** [comment]
Thanks for this!
