### ISSUE TITLE
qc results read error

### ISSUE THREAD

**Issue by royfrancis** [hartleys/QoRTs#43]
I get this error when I read in qorts data

```
qortsdata <- read.qc.results.data("",decoder=decoder,calc.DESeq2=F,calc.edgeR=F,debugMode=F)
reading QC.summary.txt files...
Error tripped on file: ./qorts/142/142_a01-qorts/QC.summary.txt
Error in read.table(infiles[i], header = T, stringsAsFactors = F) : 
  more columns than column names
```

I have run this before and it worked. Today I went back after a few months and ran this again and I run into this issue. I was wondering if this a bug or some issue on my side. Running QoRTs_1.1.8.

**Comment by hartleys** [comment]
My guess would be to try running the newest version of QoRTs (v1.2.42). JunctionSeq was supposed to be back-compatible with older QoRTs files, but it's possible some incompatibility snuck in.

What version of R/JunctionSeq are you using?

**Comment by hartleys** [comment]
EDIT: I was misremembering version numbers. This shouldn't be caused by the QoRTs version. It must be something else. Maybe the QC.summary.txt file got edited somehow? Even just reading it into excel and then saving it (even if you don't touch anything) will sometimes cause bad formatting issues, since excel attempts to automatically recognize formats.

Can you post the file "./qorts/142/142_a01-qorts/QC.summary.txt"?

**Comment by royfrancis** [comment]
Here is the file. This was generated using qorts-1.2.26.jar.

[QC.summary.txt](https://github.com/hartleys/QoRTs/files/1252347/QC.summary.txt)

**Comment by hartleys** [comment]
Ah. That's your problem then. The QoRTs R packages are NOT forward-compatible. 

If you create a file with the  v1.2.26 Java JAR, then you must use a v1.2.26+ R package.

**Comment by royfrancis** [comment]
Aha. ok. I am not going to rerun QoRTs on all my BAM files again. So I guess I have to go back to an older version of the R package.

**Comment by hartleys** [comment]
A newer version you mean. Your R package is older than the QoRTs Jar.

You can install v1.2.26 using the R command:

    install.packages("http://hartleys.github.io/QoRTs/archive/v1.2.26/QoRTs_LATEST.tar.gz",
                   repos=NULL, 
                   type="source");

**Comment by hartleys** [comment]
But actually the current version would be better. So just use the command:

    install.packages("http://hartleys.github.io/QoRTs/QoRTs_LATEST.tar.gz",
                   repos=NULL, 
                   type="source");

**Comment by royfrancis** [comment]
Oh right, I need a newer version of the R package. Then, that is still weird, because I just installed the latest version yesterday using this line:

install.packages("http://hartleys.github.io/QoRTs/QoRTs_STABLE.tar.gz",
                   repos=NULL, type="source")

But, in R it shows 1.1.8.

**Comment by hartleys** [comment]
Ah. Yeah. Many of the functions are still a bit new, so I haven't officially made these versions "stable" yet.

You want "LATEST", not "STABLE".

**Comment by royfrancis** [comment]
Ok. I will check that out. Thanks.

**Comment by royfrancis** [comment]
Yes. It works!
