### ISSUE TITLE
Hisat2 support

### ISSUE THREAD

**Issue by ctxchris** [hartleys/QoRTs#44]
Hi,

Hisat2 has become a popular RNAseq aligner and shows (at least in my experience) slightly more consistent results as STAR while also being faster. The encoding for multi-mapping reads seems to be non-standard, however, and I either get about 99% "DROPPED_NOT_UNIQUE_ALIGNMENT"reads  or 0% when I use --keepMultiMapped.

Could you add support for Hisat2?

Thanks,
Chris

**Comment by hartleys** [comment]
There is unfortunately no "standard" way to mark non-unique-aligned reads. Almost all the aligners that I am aware of use the MAPQ column to indicate multi mapping in some way, but every aligner uses its own coding. STAR marks all unique-aligned reads as 255. Tophat uses 50.

I haven't actually used HISAT2, but according to some docs I found online it looks like HISAT2 (v2.0.4 and above) uses a MAPQ of 60 to indicate unique mapping status.

So just add the parameter "--minMAPQ 60". 

Let me know if this works, and I'll update the docs with a note.

**Comment by ctxchris** [comment]
Seems to work fine.

Thanks,
Chris
