### ISSUE TITLE
Can QoRTs be used for DNASeq BAM QC?

### ISSUE THREAD

**Issue by royfrancis** [hartleys/QoRTs#48]
Can QoRTs be used for regular whole genome Illumina DNASeq BAM QC? BAM files generated from BWA aligner if that matters. And of course I don't need to generate gene counts, exon counts etc.. Is it just a matter of turning off a whole lot of modules or is there more to it?

**Comment by hartleys** [comment]
I have been using it on whole-exome-seq for the last year. 

That is why I added the "--DNA" option and all the mismatch metrics. The DNA option basically just does exactly what you say: it turns off a bunch of modules. You can also obviously just turn them off manually, or even turn any of them back on again.

**Comment by royfrancis** [comment]
Ok. Thanks. About mapping quality, I think BWA has a max mapping quality of 60. So if I use `--minMAPQ 60`, alignments below 60 is not considered? Shouldn't I be using something like `--maxMAPQ 60`?

**Comment by hartleys** [comment]
Yes, if you set it to 60, then it'll only process reads that have a MAPQ of 60. You probably want to set it lower than that, to filter out low-quality mapping while still allowing a good proportion of your reads to pass. I've never used BWA for genome-wide analysis, so I'm not sure what would be a reasonable threshold.

Why would you want to set a maxMAPQ? Higher MAPQ is better, no?

**Comment by royfrancis** [comment]
Well. If I don't set minMAPQ, I get errors possibly because QoRTs thinks that mapq goes up to 255 (Even though I use --DNA). maxMAPQ is to let QoRTs know what is the highest possible mapping quality in my BAM file. The end result of QoRTs in this case is just QC and no output from QoRTS is used for anything downstream (different from RNA-Seq). All I need QoRTs to do here is to report a summary of mapq in the BAM file.

**Comment by hartleys** [comment]
There's nothing wrong with BWA, it just isn't what my group uses (for whatever reason).

By default, QoRTs filters out all reads with a MAPQ less than minMAPQ. By default, minMAPQ is set to 255 (because this is what STAR expects).

If you want to include all reads regardless of mapq, then use the parameter "--minMAPQ 0". Then it will use all reads.

-Steve
