### ISSUE TITLE
no output for "--runFunctions StrandCheck,GeneCalcs"

### ISSUE THREAD

**Issue by ccshao** [hartleys/QoRTs#52]
Hello, 

QoRTs didn't provide output for StrandCheck,GeneCalcs on bam files generated by STAR. 
Bam files have been sorted by coordinate. I am using the stable QoRTs and  R 3.4.1 

Here are the commands:
```
java -jar /home/tools/QoRTs-STABLE.jar QC \
	--runFunctions StrandCheck,GeneCalcs \
        --maxReadLength 100 \
	--generatePlots \
	SRR3936007.Aligned.sortedByCoord.out.bam \
	$hg19gtf \
	./SRR3936007_QoRTs/

```
The error in log file are 
 ```
 > PLOTTING ERROR: Error in .External2(C_X11, paste0("png::", filename), g$width, g$height, : unable to start device PNG
   > 
   > Error in dev.off() : cannot shut down device 1 (the null device)
   > Calls: makeMultiPlot.basic ... tryCatchOne -> <Anonymous> -> devCloseFunct -> dev.off
```

The full log and R plot log are [here](https://www.dropbox.com/s/u08sqfv3ktphd64/Archive.zip?dl=0)

Thanks!

**Comment by hartleys** [comment]
Can you attach the QC.makeMultiplot.R file?

**Comment by ccshao** [comment]
Thanks for your time, here are files:

The R file:
https://www.dropbox.com/s/pur24a8x8fobmok/QC.makeMultiplot.R?dl=0

And the summary file:
https://www.dropbox.com/s/03sumn3nspm8z9v/QC.summary.txt?dl=0

**Comment by hartleys** [comment]
It looks like there might be something wrong with your R installation? 

Have you tested out the "png" function in R? Like, for example, try testing the following code in R:

    png("test.png",height=480,width=480,units="px",res=300);
    plot(1,1);
    dev.off();

**Comment by ccshao** [comment]
Indeed it does not work!
But `png("test.png", type="cairo") `works, how to let the QoRTs add (type="cairo") to all png command?

**Comment by hartleys** [comment]
You're going to need to run the R script separately. The QoRTs jar just does basic plotting, for special options you have to make a separate run.

You just need to add the option: plotting.device.params=list(type="cairo") to the makeMultiPlot commands.

    library(QoRTs);
    unique.ID <- c("Untitled");
    qc.data.dir <- c("./SRR3936007_QoRTs//");
    qc.data.prefix <- c("");
    decoder.raw <- data.frame(unique.ID = as.character(unique.ID), qc.data.dir = as.character(qc.data.dir), qc.data.prefix=as.character(qc.data.prefix),stringsAsFactors=FALSE);
    decoder <- completeAndCheckDecoder(decoder = decoder.raw)
    message(decoder);
    message(lapply(names(decoder), function(n){ class(decoder[[n]]) }));
    res <- read.qc.results.data("", decoder = decoder, calc.DESeq2 = FALSE, calc.edgeR = FALSE);
    makeMultiPlot.basic(res, outfile = "./SRR3936007_QoRTs//QC.multiPlot.png", plotter.params = list(std.color = "blue", std.lines.lwd = 4), plot.device.name = "png", plotting.device.params=list(type="cairo"));

Only the last line is different from the original QC.makeMultiplot.R file.

That should do it.

**Comment by ccshao** [comment]
Do you mean I run the R scipts myself?
I tried `R CMB BATCH QC.makeMultiplot.R`, however, it seems the intermediate are not available. I am not sure whether they were delelted by QoRTs or not generated at all. 

Here is the what the script looks like:
```
# This is an automatically-generated R script designed to make a simple multiplot and/or pdf report for a sample.
message("STARTING...");
library(QoRTs);
unique.ID <- c("Untitled");
qc.data.dir <- c("./SRR3936007_QoRTs/");
qc.data.prefix <- c("");
decoder.raw <- data.frame(unique.ID = as.character(unique.ID), qc.data.dir = as.character(qc.data.dir), qc.data.prefix=as.character(qc.data.prefix),stringsAsFactors=FALSE);
decoder <- completeAndCheckDecoder(decoder = decoder.raw)
message(decoder);
message(lapply(names(decoder), function(n){ class(decoder[[n]]) }));
res <- read.qc.results.data("", decoder = decoder, calc.DESeq2 = FALSE, calc.edgeR = FALSE);
makeMultiPlot.basic(res, outfile = "./SRR3936007_QoRTs/QC.multiPlot.png", plotter.params = list(std.color = "blue", std.lines.lwd = 4), plot.device.name = "png", plotting.device.params=list(type="cairo"));
makeMultiPlot.basic(res, outfile = "./SRR3936007_QoRTs/QC.multiPlot.pdf", plotter.params = list(std.color = "blue", std.lines.lwd = 4), plot.device.name = "pdf");
makeMultiPlot.basic(res, outfile.dir = paste0("./SRR3936007_QoRTs","QCplots/"), plotter.params = list(std.color = "blue", std.lines.lwd = 4), plot.device.name = "png", separatePlots = TRUE, plotting.device.params=list(type="cairo"));
message("DONE...");
```

and the error message:
```
> # This is an automatically-generated R script designed to make a simple multiplot and/or pdf report for a sample.
> message("STARTING...");
STARTING...
> library(QoRTs);
> unique.ID <- c("Untitled");
> qc.data.dir <- c("./SRR3936007_QoRTs/");
> qc.data.prefix <- c("");
> decoder.raw <- data.frame(unique.ID = as.character(unique.ID), qc.data.dir = as.character(qc.data.dir), qc.data.prefix=as.character(qc.data.prefix),stringsAsFactors=FALSE);
> decoder <- completeAndCheckDecoder(decoder = decoder.raw)
> message(decoder);
Untitled./SRR3936007_QoRTs/UntitledUNKNOWNUNKNOWN
> message(lapply(names(decoder), function(n){ class(decoder[[n]]) }));
charactercharactercharactercharactercharactercharacter
> res <- read.qc.results.data("", decoder = decoder, calc.DESeq2 = FALSE, calc.edgeR = FALSE);
Note: no input.read.pair.count column found. This column is optional, but without it mapping rates cannot be calculated.
Note: no multi.mapped.read.pair.count column found. This column is optional, but without it (depending on how your aligner implements multi-mapping) multi-mapping rates might not be plotted.
WARNING: QoRTs run absent! Dir not found: ./SRR3936007_QoRTs/!
Error in read.in.results.data.with.decoder(decoder = decoder.final, infile.dir = infile.dir,  : 
  Fatal error: QoRTs run data not found! Use autodetectMissingSamples = TRUE to automatically skip these runs
Calls: read.qc.results.data -> read.in.results.data.with.decoder
Execution halted


```

**Comment by ccshao** [comment]
Now I understand it. Would be convenient to change the plot device in the command line.

**Comment by ccshao** [comment]
Now I understand it, would be convenient to change the device from the command line.

**Comment by mya2152** [comment]
There must be a way to change the directory to let it to run someplace else. I have R on my laptop and I've downloaded all the QoRTs_output files locally and want to run the R scripts locally. Surely there's a parameter(s) that can be changed somewhere to allow this?
