### ISSUE TITLE
When using bash less, the timestamp and text overlap. Not really a issue (very minor).

### ISSUE THREAD

**Issue by sahilseth** [hartleys/QoRTs#7]
If I use

```
java -jar qorts.jar --man QC
```

The timestamp overlaps (`Done. (Thu Nov 05 15:50:16 CST 2015)`) with the help text.

```
    decoderFile
        The decoder file, which must conform to the requirements of
        the QoRT decoder specification. In particular it MUST have
        two specific columns:
        "sample.IDDone. (Thu Nov 05 15:47:51 CST 2015)
": This utility will merge the count data output
        from all bamfiles that have the same sample.ID
        and
```

**Comment by hartleys** [comment]
"less" does not block stderr from printing to the console. The "Done" notification prints to stderr, which puts it on top of the text that less displays.

There are a lot of options for fixing this. The easiest is to just scroll down then up again, less will overwrite the offending text.

Alternatively you can just add the "--quiet" option to turn off the "Done" notification.

**Comment by sahilseth** [comment]
Going up and down, was not helping. But `--quiet` did the trick!
