### ISSUE TITLE
Is version 1.3.6 stable?

### ISSUE THREAD

**Issue by rspreafico-vir** [hartleys/QoRTs#71]
Hi there,

is version 1.3.6 stable? If so, can it be formally tagged such that popular third-party projects such as bioconda are allowed to grab a stable version for easy redistribution?

Thanks,
Roberto

**Comment by hartleys** [comment]
Yes. 

I've now posted 1.3.6 as a stable release.

**Comment by rspreafico-vir** [comment]
Thanks!
