### ISSUE TITLE
Exception: SYNTAX ERROR! 

### ISSUE THREAD

**Issue by IlariaPalmi** [hartleys/QoRTs#80]
Dear all
I am runnnig a QC on some bam files and I get some error
CAn you please help me?
thanks

java -Xmx4G -jar $RDS/home/anaconda3/pkgs/qorts-1.3.6-0/share/qorts-1.3.6-0/QoRTs.jar QC  \
--generatePlots \
--genomeFA $RDS/projects/sequ/live/Genecode/mouseannotation/GRCm38.primary_assembly.genome.fa \
$RDS/projects/sequ/live/mapped/Genecodesecondpass/EE_Sample_SDG1Aligned.sortedByCoord.out.bam \
$RDS/projects/sequ/live/Genecode/mouseannotatio/gencode.vM25.primary_assembly.annotation.gtf \
$RDS/projects/sequ/live/mapped/QoRT_QC/ \
--readGroup

and I get the following message:
INPUT_COMMAND(QC)
  INPUT_ARG(infile)=/rds/general/user/ipalmisa/projects/sequ/live/Genecode/mouseannotatio/gencode.vM25.primary_assembly.annotation.gtf
  INPUT_ARG(gtffile)=/rds/general/user/ipalmisa/projects/sequ/live/mapped/QoRT_QC/
  INPUT_ARG(outdir)=--readGroup
  INPUT_ARG(generatePlots)=true
  INPUT_ARG(genomeFA)=Some(List(/rds/general/user/ipalmisa/projects/sequ/live/Genecode/mouseannotation/GRCm38.primary_assembly.genome.fa))
<====== FATAL ERROR! ======>
----------------------------
     Error message: "SYNTAX ERROR! Unrecognized Argument: /rds/general/user/ipalmisa/projects/sequ/live/mapped/Genecodesecondpass/EE_Sample_SDG1Aligned.sortedByCoord.out.bam"
     Stack Trace:
        java.base/java.lang.Thread.getStackTrace(Thread.java:1606)
        internalUtils.Reporter$.error(Reporter.scala:331)
        internalUtils.commandLineUI$.internalUtils$commandLineUI$$throwSyntaxErrorMessage(commandLineUI.scala:328)
        internalUtils.commandLineUI$CommandLineArgParser.parseParamArgs(commandLineUI.scala:314)
        internalUtils.commandLineUI$CommandLineArgParser.parseArgs_master(commandLineUI.scala:287)
        internalUtils.commandLineUI$CommandLineArgParser.parseArguments(commandLineUI.scala:152)
        qcUtils.runAllQC$allQC_runner.run(runAllQC.scala:631)
        runner.runner$.main(runner.scala:98)
        runner.runner.main(runner.scala)
<==========================>
Exception in thread "main" java.lang.Exception: SYNTAX ERROR! Unrecognized Argument: /rds/general/user/ipalmisa/projects/sequ/live/mapped/Genecodesecondpass/EE_Sample_SDG1Aligned.sortedByCoord.out.bam
	at internalUtils.Reporter$.error(Reporter.scala:336)
	at internalUtils.commandLineUI$.internalUtils$commandLineUI$$throwSyntaxErrorMessage(commandLineUI.scala:328)
	at internalUtils.commandLineUI$CommandLineArgParser.parseParamArgs(commandLineUI.scala:314)
	at internalUtils.commandLineUI$CommandLineArgParser.parseArgs_master(commandLineUI.scala:287)
	at internalUtils.commandLineUI$CommandLineArgParser.parseArguments(commandLineUI.scala:152)
	at qcUtils.runAllQC$allQC_runner.run(runAllQC.scala:631)
	at runner.runner$.main(runner.scala:98)
	at runner.runner.main(runner.scala)

**Comment by IlariaPalmi** [comment]
sorry, I had closed it by mistake

**Comment by IlariaPalmi** [comment]
I understood that the --readGroup option was the problem (it runs fine if I don't use this option). can you please explain me how to use it properly? The bam file has been generate via STAR using different fastq files
Thanks

**Comment by sparthib** [comment]
Hi @IlariaPalmi, this is probably too too late, but I ran into the same issue and I think all the file arguments have to be at the end, 
so, if you rewrote your code as 

```
java -Xmx4G -jar $RDS/home/anaconda3/pkgs/qorts-1.3.6-0/share/qorts-1.3.6-0/QoRTs.jar QC
--generatePlots \
--readGroup \
--genomeFA $RDS/projects/sequ/live/Genecode/mouseannotation/GRCm38.primary_assembly.genome.fa \
$RDS/projects/sequ/live/mapped/Genecodesecondpass/EE_Sample_SDG1Aligned.sortedByCoord.out.bam \
$RDS/projects/sequ/live/Genecode/mouseannotatio/gencode.vM25.primary_assembly.annotation.gtf \
$RDS/projects/sequ/live/mapped/QoRT_QC/
```

it should run
