### ISSUE TITLE
Question regarding a few gff files

### ISSUE THREAD

**Issue by sahilseth** [hartleys/QoRTs#9]
I see a few files in the example  walk-though, was wondering the source for them; and also how were they generated.

- forJunctionSeq.gff.gz
- forDEXSeq.gff.gz
- withNovel.forJunctionSeq.gff.gz
- orphanSplices.gff.gz

Thanks!

**Comment by sahilseth** [comment]
found the script, step6A.makeFlatAnnoFiles.sh

**Comment by hartleys** [comment]
forJunctionSeq.gff and forDexSeq.gff are produced by the java jar command:
makeFlatGff ( found here:
http://hartleys.github.io/QoRTs/jarHtml/makeFlatGff.html ). The dexseq
version requires the --DEXSeqFmt option.

withNovel.forJunctionSeq.gff and orphanSplices.gff are generated by the
mergeNovelSplices command ( see here:
http://hartleys.github.io/QoRTs/jarHtml/mergeNovelSplices.html )

Make sure you are using the most recent version of QoRTs.
